blueprint:
  name: Home Assistant Cover Position to Loxone
  description: Send entity states from Home Assistant to Loxone
  domain: automation
  input:
    target_miniserver:
      name: Miniserver Address/DNS Name
      selector:
        text: {}
    target_miniserver_user:
      name: Miniserver User
      selector:
        text: {}
    target_miniserver_password:
      name: Miniserver Password
      selector:
        text:
          type: password
          multiple: false
          multiline: false
    target_entities:
      name: Trigger entities
      description: List the entities that will be sent to the VI's on the Miniserver
      selector:
        entity:
          multiple: true
          filter:
          - domain:
            - cover
  source_url: https://github.com/philipphell/ha2loxone/blob/ed42d6635a87d62a31c9d6bbf939d852ad55bca6/blueprints/cover__current_position.yaml
alias: Update Loxone (Cover Position)
description: ''
trigger:
- platform: state
  entity_id: !input target_entities
condition: []
action:
- service: rest_command.update_loxone
  data:
    miniserver: !input target_miniserver
    username: !input target_miniserver_user
    password: !input target_miniserver_password
    parameter: '{{ trigger.entity_id  }}/{{ trigger.to_state.attributes.current_position  }}'
mode: parallel
